### ISSUE TITLE
Иногда крашится app, jivo sdk инициализирован по инструкцию

### ISSUE THREAD

**Issue by Qutbiddin** [JivoChat/JivoSDK-Android#39]
Fatal Exception: java.lang.RuntimeException: Unable to create service com.jivosite.sdk.socket.JivoWebSocketService: kotlin.UninitializedPropertyAccessException: lateinit property jivoSdkComponent has not been initialized
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4083)
       at android.app.ActivityThread.access$1800(ActivityThread.java:232)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Qutbiddin** [comment]
давно решили)
сделали функцию в Application и вызвали после инициализации необходимых компонентов

**Comment by Kooo9058** [comment]
> давно решили) сделали функцию в Application и вызвали после инициализации необходимых компонентов

Подскажите как решили проблему падения ?

**Comment by tavtorkin-jivo** [comment]
> Наблюдаю такое же падение приложения, только в моём случае инит живочата происходит дальше чем в классе Application. Контекст передаю глобальный, но андроид чистит из памяти object. Пожалуйста, подскажите решение данной проблемы

Добрый день! Мы не гарантируем корректную работу SDK, если вы пытаетесь вызвать `Jivo.init()` не в классе унаследованном от `Application`
Можете пояснить, с какой целью вы вызываете  `Jivo.init()`  не в классе унаследованном от `Application` ?

**Comment by Kooo9058** [comment]
> 
widgetId изменяется динамически, и получение id происходит позднее чем инит живочата. Поэтому инит делаем по приходу id с бэка. 
Есть мысль сделать статику у класса App, а после ее подтягивать в момент инициализации живочата. Насколько правильным будет такое решение? 

class App : Application {
 companion object {
        lateinit var INSTANCE: App 
        
 } 
 
Поздней подтягивать инстанс класса app
      Jivo.init(
            appContext = App.INSTANCE,
            widgetId = id

        )

**Comment by Qutbiddin** [comment]
> > Наблюдаю такое же падение приложения, только в моём случае инит живочата происходит дальше чем в классе Application. Контекст передаю глобальный, но андроид чистит из памяти object. Пожалуйста, подскажите решение данной проблемы
> 
> Добрый день! Мы не гарантируем корректную работу SDK, если вы пытаетесь вызвать `Jivo.init()` не в классе унаследованном от `Application` Можете пояснить, с какой целью вы вызываете `Jivo.init()` не в классе унаследованном от `Application` ?

будет ли в будущем возможность задавать widgetId после Jivo.init() ?

**Comment by Qutbiddin** [comment]
> > давно решили) сделали функцию в Application и вызвали после инициализации необходимых компонентов
> 
> Подскажите как решили проблему падения ?

fcvJivo.post {
                **childFragmentManager**
                    .beginTransaction()
                    .replace(R.id.fcvJivo, JivoChatFragment())
                    .commit()
            }
передайте child вместе parrent fragment

**Comment by tavtorkin-jivo** [comment]
> 

Да, мы планируем динамическую смену widgetId.

**Comment by Kooo9058** [comment]
> > > давно решили) сделали функцию в Application и вызвали после инициализации необходимых компонентов
> > 
> > 
> > Подскажите как решили проблему падения ?
> 
> fcvJivo.post { **childFragmentManager** .beginTransaction() .replace(R.id.fcvJivo, JivoChatFragment()) .commit() } передайте child вместе parrent fragment

Прошу дать развернутый ответ:) ибо не до конца понятно, причём тут фрагмент менеджер.

**Comment by Kooo9058** [comment]
> давно решили) сделали функцию в Application и вызвали после инициализации необходимых компонентов

Возможно ли с вами связаться для краткой консультации?:)

**Comment by tavtorkin-jivo** [comment]
@Qutbiddin @Kooo9058 Добрый день коллеги! Вышло обновление SDK 1.2.0, добавлена возможность смены канала. Подробнее по [ссылке](https://github.com/JivoChat/JivoSDK-Android/blob/develop/README.md#%D1%81%D0%BC%D0%B5%D0%BD%D0%B0-%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B0-%D1%87%D0%B0%D1%82%D0%B0).

**Comment by Qutbiddin** [comment]
заработал, спасибо!
