### ISSUE TITLE
Не сохранятеся история чата после удаления apk

### ISSUE THREAD

**Issue by fuzayl98** [JivoChat/JivoSDK-Android#43]
Добрый день! Я генерировал JWT токен и отправил его в Jivo SDK. Потом удалил apk и снова установил, отправил JWT токен но история чата не восстанавливается :( В чем может быть проблема? Заранее спасибо 😉

**Comment by tavtorkin-jivo** [comment]
Добрый день! А вы передавали нам SECRET?  И у вас есть возможность прислать JWT-токен?

**Comment by fuzayl98** [comment]
SECRET у вас стринг? Jivo.setUserToken() через этот метод в отправлю JWT. Еще что то нужно?

**Comment by tavtorkin-jivo** [comment]
SECRET это набор символов, выглядит как обычный пароль. SECRET нужно сгенерировать и передать нам. На JWT-токен тоже хотелось бы посмотреть.

**Comment by fuzayl98** [comment]
Что бы предоставить SECRET какой метод используется? Предоставить вам JWT?

**Comment by dzolotarev** [comment]
@fuzayl98 Добрый день! Прошу прощения за задержку с ответом. Свяжитесь, пожалуйста, с нами напрямую для уточнения деталей по данному вопросу - android@jivosite.com с темой "Вопрос по JWT в mobile SDK". Спасибо.
