### ISSUE TITLE
Не приходят пуши, когда приложение закрыто

### ISSUE THREAD

**Issue by VITYQ** [JivoChat/JivoSDK-Android#52]
При свернутом и закрытом приложении не приходят пуши от чата, в чем может быть проблема?
При этом на открытом приложении пуши приходят. 
Настраивали как указано в документации. Admin SDK ключ сгенерировали. 

Заранее спасибо

**Comment by tavtorkin-jivo** [comment]
@VITYQ Здравствуйте!
Можете [включить](https://github.com/JivoChat/JivoSDK-Android/blob/develop/README_ru.md#%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BB%D0%BE%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) логи SDK ?
Требуется больше информация, какая версия OS, устройство, версия SDK?

**Comment by mitaichik** [comment]
> При свернутом и закрытом приложении не приходят пуши от чата, в чем может быть проблема? При этом на открытом приложении пуши приходят. Настраивали как указано в документации. Admin SDK ключ сгенерировали.
> 
> Заранее спасибо

Получилось разобраться. Я уже перепроверил все что только можно - они реально не приходят, такое чувство, что Jivo их и не отправляют.
