### ISSUE TITLE
Could not find com.github.chrisbanes:PhotoView:2.3.0. Searched in the following locations: - https://dl.google.com/dl/android/maven2/com/github/chrisbanes/PhotoView/2.3.0/PhotoView-2.3.0.pom -

### ISSUE THREAD

**Issue by KhusniddinovKhumoyun** [JivoChat/JivoSDK-Android#56]

**Comment by KhusniddinovKhumoyun** [comment]
i added this dependences //JivoSDK     implementation 'com.jivosite.sdk:android-sdk:1.0.0'     implementation 'com.github.chrisbanes:PhotoView:2.3.0' in gradle module   and  in buildScript block i added   repositories {         google()         mavenCentral()     }  and i have build error  like this  Could not find com.github.chrisbanes:PhotoView:2.3.0.      Searched in the following locations:        - https://dl.google.com/dl/android/maven2/com/github/chrisbanes/PhotoView/2.3.0/PhotoView-2.3.0.pom        - https://repo.maven.apache.org/maven2/com/github/chrisbanes/PhotoView/2.3.0/PhotoView-2.3.0.pom

**Comment by tavtorkin-jivo** [comment]
@KhusniddinovKhumoyun Hello! What version of SDK do you use?

**Comment by tavtorkin-jivo** [comment]
Did you make these settings? Add this in your root build.gradle file (not your module build.gradle file):

```
allprojects {
    repositories {
        maven { url "https://www.jitpack.io" }
    }
}

buildscript {
    repositories {
        maven { url "https://www.jitpack.io" }
    }	
}
```

**Comment by KhusniddinovKhumoyun** [comment]
I used 33 sdk version

**Comment by tavtorkin-jivo** [comment]
> 

What version of JivoSDK do you use?

**Comment by KhusniddinovKhumoyun** [comment]
1.0.0

**Comment by tavtorkin-jivo** [comment]
> 1.0.0
This is a very old version of JivoSDK. Use the latest version of JivoSDK. 1.2.1

**Comment by KhusniddinovKhumoyun** [comment]
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.5.3'
    }
}

plugins {
    id 'com.android.application' version '7.3.0' apply false
    id 'com.android.library' version '7.3.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.10' apply false
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

this is my root build.gradle file. I didn't use 

allprojects {
    repositories {
        maven { url "https://www.jitpack.io" }
    }
}

buildscript {
    repositories {
        maven { url "https://www.jitpack.io" }
    }	
}

because maven is deprecated.My project wasn't built.It shows me same error that I wrote in issue

**Comment by KhusniddinovKhumoyun** [comment]
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.5.3'
    }
}

plugins {
    id 'com.android.application' version '7.3.0' apply false
    id 'com.android.library' version '7.3.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.10' apply false
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

this is my root build.gradle file. I didn't use  these: 

allprojects {
    repositories {
        maven { url "https://www.jitpack.io" }
    }
}

buildscript {
    repositories {
        maven { url "https://www.jitpack.io" }
    }	
}

because maven is deprecated.My project wasn't built.It shows me same error that I wrote in issue
