### ISSUE TITLE
Is it possible to show push notifications when the application is in the background or closed?

### ISSUE THREAD

**Issue by anastasiyaK97** [JivoChat/JivoSDK-Android#59]
I'm trying to set up push notifications when the app is in background or closed.
Jivo version 1.2.1
When my app is running on the foreground, push notifications is shown **correctly**. Permission "Display pop-up windows while running in the background" in app settings were granted.
If app in background notification is not appears on the status bar. According to Firebase documentation, notifications should be recieved.

**Comment by tavtorkin-jivo** [comment]
Hello!
Do you have the Firebase Cloud Messaging API enabled?
Enable it by visiting https://console.developers.google.com/apis/api/fcm.googleapis.com/overview?project=your_project_id then retry.

**Comment by anastasiyaK97** [comment]
@tavtorkin-jivo  Hello! Thanks for the answer. There was a problem with the channel key.
