### ISSUE TITLE
Поддержка Flutter'a 

### ISSUE THREAD

**Issue by zhukeev** [JivoChat/JivoSDK-Android#60]
Планируется ли поддержка Flutter'a ? 
Я сейчас начал делать на Flutter'e библиотеку для чата, могу ли я использовать Ваши сокет эндпоинты ? (ниже)
```
override fun getEndpoint(): URI {
        return storage.path.let {
            if (it.isBlank()) {
                URI.create(
                    "wss://${storage.chatserverHost}/atom/" +
                            "${storage.siteId}:" +
                            storage.widgetId.ifBlank { sdkContext.widgetId } +
                            getQuery(sdkContext.userToken)
                )
            } else {
                URI.create("wss://${storage.chatserverHost}/atom${it}")
            }
        }
    }

    private fun getQuery(userToken: String) = if (userToken.isNotBlank()) """?token=${userToken}""" else ""
```
 Есть ли у вас discord/slack каналы для дальнейших вопросов ? 

Спасибо.

**Comment by dzolotarev** [comment]
Здравствуйте!
Реализации Jivo Mobile SDK на Flutter в ближайшее время не планируется. Вы можете использовать нативную библиотеку в вашем Flutter приложении. 
Напишите, пожалуйста, на android@jivo.ru и мы организуем канал для дальнейших коммуникаций.
