### ISSUE TITLE
Вопросы по настройке для RN

### ISSUE THREAD

**Issue by kotoyama** [JivoChat/JivoSDK-Android#66]
Я выполнила настройку для RN из соответствующей секции, также создала проект в Firebase и привязала ключ к SDK для настройки пушей. Сейчас все ок, активность запускается, я вижу чат. Правильно ли я понимаю, что, чтобы заработали пуши, одного лишь вызова `openJivoSdk` в реакт компоненте недостаточно? Нужно ли мне дополнительно запрашивать пермишены на пуши и как-то обрабатывать их, как описано в секциях, не относящихся к RN?

Также подскажите, пожалуйста, могу ли я как-то протестировать работоспобность SDK в деве (включая пуши), не тревожа реальных операторов.
Спасибо!

**Comment by tavtorkin-jivo** [comment]
Добрый день! 
Все верно, вам следует полностью выполнить [настройки push notifications ](https://github.com/JivoChat/JivoSDK-Android/blob/develop/README_ru.md#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-push-notifications)

Вам нужно скопировать файл конфигурации(google-services.json) в каталог модуля (уровня приложения) вашего приложения.

А так же добавить настройки: 

**- app/build.gradle:**
```
apply plugin: 'com.google.gms.google-services' 
...

dependencies {
...
    implementation platform('com.google.firebase:firebase-bom:32.1.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics-ktx'
}
```
**- android/build.gradle:**
```
buildscript {
...
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.4.2')
        classpath 'com.google.gms:google-services:4.3.14'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by kotoyama** [comment]
Спасибо, я это тоже всё сделала. Кстати, у меня в процессе вылезла ошибка о том, что не хватало ассета `ic_notification_small.png`. Добавила из приложения из примера и заработало. Думаю, этот момент нужно тоже в доку внести.

То есть никаких пермишенов запрашивать не надо?

**Comment by kotoyama** [comment]
Спасибо!
