### ISSUE TITLE
Вопрос по дополнительной конфигурации

### ISSUE THREAD

**Issue by kotoyama** [JivoChat/JivoSDK-Android#67]
Возможно ли поменять или вовсе убрать вот этот тайтл "На связи 24/7"?

![telegram-cloud-photo-size-2-5229011563942366328-y](https://github.com/JivoChat/JivoSDK-Android/assets/26006369/17d3dc82-3533-4cd7-b54f-ff3de7d68343)

**Comment by tavtorkin-jivo** [comment]
Добрый день! 
Вы можете переопределить стиль `Widget.JivoSDK.Toolbar` подробнее в [документации ](https://github.com/JivoChat/JivoSDK-Android/blob/develop/README_ru.md#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-ui-jivosdk). Пример реализации можно посмотреть в [sample](https://github.com/JivoChat/JivoSDK-Android/blob/develop/sample/src/main/res/values/style.xml).
