### ISSUE TITLE
Does history works now?

### ISSUE THREAD

**Issue by 4KNikitaBorysov** [JivoChat/JivoSDK-Android#75]
Readme says, that we need provide secret key to jivo, but also mention that there is no interface for that.

**Comment by tavtorkin-jivo** [comment]
Hello!
You can pass secret key  thought the Jivo desktop/web app in the SDK channel settings.
See NOTE https://github.com/JivoChat/JivoSDK-Android/blob/develop/README_en/native_api.md#jivosetdata
