### ISSUE TITLE
JivoSDK crashes application

### ISSUE THREAD

**Issue by CesPaul** [JivoChat/JivoSDK-Android#76]
SDK version 2.4.0
Kotlin version 1.6.10
Gradle 7.1.1

При загрузке непустого чата, происходит ошибка ([JivoSDKError.txt](https://github.com/user-attachments/files/17296811/JivoSDKError.txt)).
Были соблюдены рекомендации по Proguard и Auto Backup, которые указаны в https://github.com/JivoChat/JivoSDK-Android/blob/develop/README_ru/recommendations.md
Начиная с версии JivoSDK 1.1.0 эта ошибка происходит.
Такой ошибки не происходит в версии JivoSDK 1.0.7 .

**Comment by tavtorkin-jivo** [comment]
@CesPaul Можете попробовать настройки Proguard для okhttp3:
https://raw.githubusercontent.com/square/okhttp/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro

**Comment by tavtorkin-jivo** [comment]
Добрый день! Можете обновить JivoSDK до версии 2.5.0, в текущей версии String.toLongOrDefault() не используется от OkHttp.
